#include "/Engine/Public/Platform.ush"
#include "/Engine/Private/Common.ush"

float4 SimpleColor;

void MainVS(
	in uint VertexId : SV_VertexID,
	in float4 InPosition : ATTRIBUTE0,
	out float4 OutPosition : SV_POSITION)
{
	OutPosition = InPosition;

	// Draw quads
	// float2 LocalUV = float2(((VertexId + 1) / 3) & 1, VertexId & 1);
	// LocalUV = LocalUV * 2.f - 1.f;
	// OutPosition = float4(LocalUV, 0, 1);
}

void MainPS(
	out float4 OutColor : SV_Target0)
{
	OutColor = SimpleColor;
}
